// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'login': string;
  'logoBox': string;
  'tips': string;
}
declare var cssExports: CssExports;
export = cssExports;
