// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centered': string;
  'emoji': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
