// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'message': string;
  'messageHeader': string;
}
declare var cssExports: CssExports;
export = cssExports;
