// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autoComplete': string;
  'btnCover': string;
  'content': string;
  'reset': string;
  'textContent': string;
}
declare var cssExports: CssExports;
export = cssExports;
