// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'right': string;
  'rightIcon': string;
  'trigger': string;
}
declare var cssExports: CssExports;
export = cssExports;
