// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autoComplete': string;
  'btn': string;
  'btnCover': string;
  'checkbox': string;
  'connect': string;
  'container': string;
  'content': string;
  'handler': string;
  'head': string;
  'reset': string;
  'socketUrlInput': string;
  'textContent': string;
  'tips': string;
}
declare var cssExports: CssExports;
export = cssExports;
