// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'changeTheme': string;
  'dark': string;
  'logoBox': string;
  'menu': string;
  'sider': string;
}
declare var cssExports: CssExports;
export = cssExports;
