// This file is automatically generated.
// Please do not change this file!
export const changeTheme: string;
export const dark: string;
export const logoBox: string;
export const menu: string;
export const sider: string;
