// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'checkbox': string;
  'connect': string;
  'container': string;
  'tips': string;
}
declare var cssExports: CssExports;
export = cssExports;
