// This file is automatically generated.
// Please do not change this file!
export const avatars: string;
export const avatarsContainer: string;
export const dashboard: string;
export const test: string;
