// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatars': string;
  'avatarsContainer': string;
  'dashboard': string;
  'test': string;
}
declare var cssExports: CssExports;
export = cssExports;
